# -*- coding: utf-8 -*-
"""Desafio1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XlBJWNA2bom1mmkyXXHrsOOjUpxrnS6Z
"""

# Foram implementadas duas soluções
# A primeira considera somente os números "exclusivos"
# A segunda considera "todos os números"

# Primeira:

# Variável armazena os valores reversíveis exclusivos
lista_exclusivos=[]

# Retorna somente os números exclusivos (considera n e reverso(n) como o mesmo número)

# Percorre o range até 1000000 atribuindo a variável 'i' seu reverso, convertendo ambas em strings
for n in range(0,1000001):
  i=str(n)[::-1]
  n=str(n)

# Condições para adicionar os números impares à lista menores que 1000000 e em que n e reverso(n) não começem com 0
  if (int(n)+int(i)) % 2  != 0 and (int(n)+int(i)) < 1000001 and not (n.startswith('0')) and not (i.startswith('0')) :

# Condição para adicionar à lista somente o número que seu reverso não esteja previamente nela
    if i not in lista_exclusivos:
      lista_exclusivos.append(n)
    else:
       pass
  else:
    pass

# Exibe na tela os resultados
print(f'A lista com os números exclusivos reversíveis, abaixo de 1.000.000 é a seguinte:\n{lista_exclusivos}\nA lista contém {len(lista_exclusivos)} elementos')


# Segunda:

# Variável armazena os todos os valores
lista_completa=[]

# Percorre o range até 1000000 atribuindo a variável 'i' seu reverso, convertendo ambas em strings
for n in range(0,100000):
  i=str(n)[::-1]
  n=str(n)

# Condições para adicionar os números impares à lista menores que 1000000 e em que n e reverso(n) não começem com 0
  if (int(n)+int(i)) % 2  != 0 and (int(n)+int(i)) < 1000001 and not (n.startswith('0')) and not (i.startswith('0')) :
    lista_completa.append(n)
  else:
    pass

# Exibe na tela os resultados
print(f'\nA lista completa de números reversíveis, abaixo de 1.000.000 é a seguinte:\n{lista_completa}\nA lista contém {len(lista_completa)} elementos')